---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ar2832package2

<!-- badges: start -->
<!-- badges: end -->

The goal of ar2832package2 is to provide functionality for my package. These functions are for use only with Arnau Rovira and no other people

## Installation

You can install the released version of ar2832package2 from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("ar2832package2")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(ar2832package2)
## basic example code

#Prepare the data
library(data.table)
if(!file.exists("zip.train.gz")){
  download.file(
    "https://web.stanford.edu/~hastie/ElemStatLearn/datasets/zip.train.gz",
    "zip.train.gz")
}
zip.train.gz <- data.table::fread("zip.train.gz")
zip.train <- zip.train.gz[1:100,-1]

if(!file.exists("zip.test.gz")){
  download.file(
    "https://web.stanford.edu/~hastie/ElemStatLearn/datasets/zip.test.gz",
    "zip.test.gz")
}
zip.test.gz <- data.table::fread("zip.test.gz")
zip.test <- zip.test.gz[1:100,-1]

data(neuroblastoma, package="neuroblastoma")
pro.dt <- data.table(neuroblastoma[["profiles"]])
one.sequence <- pro.dt[profile.id=="4" & chromosome=="2"]


#BINSEG function
?BINSEG
binseg <- BINSEG(one.sequence$logratio, Kmax=20)
binseg


#PCA function
pca <- PCA(zip.train)
pca
pca2 <- PCA(zip.test)
pca2
```
